version: 2.1

orbs:
  artifactory:
    jobs:
      upload:
        parameters:
          docker:
            type: string
            default: 'circeci/openjdk-8' 
            description: "Docker image to use for build"
          file-spec:
            type: string
            default: ''
            description: "Optional: Path to a File Spec containing additional configuration"
          source:
            type: string
            description: "The local pattern of files to match"
          target:
            type: string
            description: "The remote path in artifactor, using pattern [repository_name]/[repository_path]"
        steps:
          - install
          - configure
          - upload:
              source: <<parameters.source>>
              target: <<parameters.target>>
              file-spec: <<parameters.file-spec>> 
        docker: 
          - image: <<parameters.docker>>
    commands:
      install:
        steps:
          - run:
              name: Install JFrog CLI
              command: |
                curl -fL https://getcli.jfrog.io | sh
      configure:
        steps:
          - run:
              name: Configure JFrog CLI
              command: |
                jfrog rt c rt-server-1 --url=${ARTIFACTORY_URL} --apikey=${ARTIFACTORY_API_KEY} --interactive=false
      upload:
        parameters:
          file-spec:
            type: string
          source:
            type: string 
          target:
            type: string 
        steps:
          - run:
              name: Upload Assets with JFrog CLI
              command: |
                if [ -s "<<parameters.file-spec>>" ];then
                  jfrog rt upload <<parameters.source>> <<parameters.target>> --spec=<<parameters.file-spec>> --build-name=${CIRCLE_PROJECT_REPONAME}   --build-number=${CIRCLE_BUILD_NUM}
                else
                  jfrog rt upload <<parameters.source>> <<parameters.target>> --build-name=${CIRCLE_PROJECT_REPONAME}   --build-number=${CIRCLE_BUILD_NUM}
                fi

workflows:
  version: 2
  test-orb:
    jobs:
      - artifactory/upload:
          name: Test Upload
          source: test/artifact.jar
          target: repo/path


