version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
          curl https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh --fail --show-error | bash
      - run:
          name: Validate
          command: circleci orb validate .circleci/orbs/artifactory.yml
      - run:
          name: Tests
          command: bash tests/runner.sh




workflows:
  version: 2
  test-orb:
    jobs:
      - test


