steps:
  - run:
      name: Configure JFrog CLI
      command: |
        : "${ARTIFACTORY_URL?Artifactory URL and API Key must be set as Environment variables before running this command.}"
        : "${ARTIFACTORY_API_KEY?Artifactory URL and API Key must be set as Environment variables before running this command.}"
        jfrog rt c rt-server-1 --url=${ARTIFACTORY_URL} --apikey=${ARTIFACTORY_API_KEY} --interactive=false
      