description: >
  etc

parameters:
  artifactory-url:
    type: env_var_name
    default: ARTIFACTORY_URL
    description: >
      etc

  artifactory-key:
    type: env_var_name
    default: ARTIFACTORY_API_KEY
    description: >
      etc

  artifactory-user:
    type: env_var_name
    default: ARTIFACTORY_USER
    description: >
      etc

steps:
  - run:
      name: Configure JFrog CLI
      command: |
        : "${<<parameters.artifactory-url>>?Artifactory URL, API Key, and User must be set as Environment variables before running this command.}"
        : "${<<parameters.artifactory-key>>?Artifactory URL, API Key, and User must be set as Environment variables before running this command.}"
        : "${<<parameters.artifactory-user>>?Artifactory URL, API Key, and User must be set as Environment variables before running this command.}"
        echo "configuring jfrog CLI with target ${<<parameters.artifactory-user>>}@${<<parameters.artifactory-url>>}"
        jfrog rt c --user=${<<parameters.artifactory-user>>} --url=${<<parameters.artifactory-url>>} --apikey=${<<parameters.artifactory-key>>} --interactive=false
