description: Configure the JFrog CLI

parameters:
  artifactory-url:
    type: env_var_name
    default: ARTIFACTORY_URL
    description: >
      Name of environment variable storing the URL of your Artifactory
      instance

  artifactory-key:
    type: env_var_name
    default: ARTIFACTORY_API_KEY
    description: >
      Name of environment variable storing your Artifactory API key

  artifactory-user:
    type: env_var_name
    default: ARTIFACTORY_USER
    description: >
      Name of environment variable storing your Artifactory username

steps:
  - run:
      name: Configure JFrog CLI
      command: |
        : "${<<parameters.artifactory-url>>?Artifactory URL, API Key, and User \
          must be set as Environment variables before running this command.}"
        : "${<<parameters.artifactory-key>>?Artifactory URL, API Key, and User \
          must be set as Environment variables before running this command.}"
        : "${<<parameters.artifactory-user>>?Artifactory URL, API Key, and User \
          must be set as Environment variables before running this command.}"

        echo "configuring jfrog CLI with target ${<<parameters.artifactory-user>>}@${<<parameters.artifactory-url>>}"

        jfrog rt c \
          --user=${<<parameters.artifactory-user>>} \
          --url=${<<parameters.artifactory-url>>} \
          --apikey=${<<parameters.artifactory-key>>} \
          --interactive=false
