version: 2.1 #feels weird this is needed in an orb file, whats the impact?
description: An orb expressing the features of the JFrog Artifactory CLI

jobs:
  upload:
    parameters:
      docker:
        type: string
        default: 'circleci/openjdk:8' 
        description: "Docker image to use for build"
      file-spec:
        type: string
        default: ''
        description: "Optional: Path to a File Spec containing additional configuration"
      source:
        type: string
        description: "The local pattern of files to match"
      target:
        type: string
        description: "The remote path in artifactor, using pattern [repository_name]/[repository_path]"
    steps:
      - install
      - configure
      - upload:
          source: <<parameters.source>>
          target: <<parameters.target>>
          file-spec: <<parameters.file-spec>> 
    
    docker: 
      - image: <<parameters.docker>>
